// Code generated by "stringer -type Status"; DO NOT EDIT.

package webcam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[Ready-1]
	_ = x[WaitingFrame-2]
	_ = x[Sleep-3]
}

const _Status_name = "IdleReadyWaitingFrameSleep"

var _Status_index = [...]uint8{0, 4, 9, 21, 26}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
